# Generated by Django 3.1 on 2020-08-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200826_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.SlugField(default='testproject'),
            preserve_default=False,
        ),
    ]
